name: NationsWRLD
main: net.minenations.nationswrld.NationsWRLD
version: 1.0
api-version: 1.17
depend: [WRLDPaymentsAPI]
commands:
  wallet:
    description: Displays player's connected wallet
  paywrld:
    description: Send $WRLD to other players
  wrldbal:
    description: Displays current $WRLD balance
  serverpaywrld:
    description: Server pays player's $WRLD